# Generated by Django 6.0.4 on 2026-04-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='images/default.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='familiya',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='ism',
            field=models.CharField(max_length=80),
        ),
    ]
